import fs from "fs";

export async function generateHTML({
  outputPath,
  reportId,
  title = "AI Analysis Report",
  summary = "",
  analysis = "",
  recommendations = "",
  sources = [],
}) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>

<style>
*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family:Arial,Helvetica,sans-serif;
}

body{
    background:#f4f6f9;
    color:#222;
    padding:40px;
}

.container{
    max-width:1100px;
    margin:auto;
    background:#fff;
    border-radius:12px;
    box-shadow:0 0 20px rgba(0,0,0,.12);
    overflow:hidden;
}

.header{
    background:#1565C0;
    color:white;
    padding:35px;
}

.header h1{
    font-size:34px;
}

.header p{
    margin-top:10px;
}

.section{
    padding:30px;
    border-bottom:1px solid #eee;
}

.section h2{
    color:#1565C0;
    margin-bottom:15px;
}

pre{
    white-space:pre-wrap;
    word-wrap:break-word;
    font-size:15px;
    line-height:1.8;
}

ul{
    padding-left:20px;
}

li{
    margin-bottom:10px;
}

.footer{
    background:#f8f8f8;
    text-align:center;
    padding:25px;
    font-size:14px;
    color:#666;
}

a{
    color:#1565C0;
    text-decoration:none;
}

a:hover{
    text-decoration:underline;
}

@media print{
    body{
        background:white;
        padding:0;
    }

    .container{
        box-shadow:none;
        border:none;
    }
}
</style>

</head>

<body>

<div class="container">

<div class="header">
<h1>TRUVORA</h1>
<p><strong>${title}</strong></p>
<p>Report ID: ${reportId}</p>
<p>Generated: ${new Date().toLocaleString()}</p>
</div>

<div class="section">
<h2>Executive Summary</h2>
<pre>${summary}</pre>
</div>

<div class="section">
<h2>Detailed Analysis</h2>
<pre>${analysis}</pre>
</div>

<div class="section">
<h2>Recommendations</h2>
<pre>${recommendations}</pre>
</div>

<div class="section">
<h2>Sources</h2>

<ul>

${sources
  .map(
    (url) => `
<li>
<a href="${url}" target="_blank">
${url}
</a>
</li>`
  )
  .join("")}

</ul>

</div>

<div class="footer">
Generated by <strong>TRUVORA Global AI</strong><br>
Intelligence • Innovation • Trust
</div>

</div>

</body>
</html>`;

  fs.writeFileSync(outputPath, html, "utf8");

  return outputPath;
}