import fs from "fs";

export async function generateMarkdown({
  outputPath,
  reportId,
  title = "AI Analysis Report",
  summary = "",
  analysis = "",
  recommendations = "",
  sources = [],
}) {
  const markdown = `# TRUVORA

## ${title}

**Report ID:** ${reportId}

**Generated:** ${new Date().toLocaleString()}

---

# Executive Summary

${summary}

---

# Detailed Analysis

${analysis}

---

# Recommendations

${recommendations}

---

# Sources

${sources.map((url) => `- ${url}`).join("\n")}

---

Generated by **TRUVORA Global AI**

Intelligence • Innovation • Trust
`;

  fs.writeFileSync(outputPath, markdown, "utf8");

  return outputPath;
}