import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { BRAND } from "../utils/branding.js";
import { prepareDocument } from "../documentGenerator.js";

function createPdf(filePath) {
  const doc = new PDFDocument({
    size: "A4",
    margins: {
      top: 70,
      bottom: 70,
      left: 20,
right: 20
    },
    bufferPages: false
  });

  doc.pipe(fs.createWriteStream(filePath));

  return doc;
}

function drawHeader(doc, reportId) {
  doc.save();

  doc.rect(0, 0, doc.page.width, 120)
     .fill(BRAND.colors.primary);

  doc.restore();

  doc
    .fillColor(BRAND.colors.white)
    .font("Helvetica-Bold")
    .fontSize(34)
    .text(BRAND.company.name, 0, 28, {
      align: "center"
    });

  doc
    .fillColor(BRAND.colors.white)
    .font("Helvetica")
    .fontSize(15)
    .text(BRAND.company.fullName, {
      align: "center"
    });

  doc.moveDown(0.3);

  doc
    .fillColor(BRAND.colors.white)
    .fontSize(12)
    .text(BRAND.company.slogan, {
      align: "center"
    });

  doc.moveDown(2);

  doc
    .fillColor(BRAND.colors.text)
    .font("Helvetica-Bold")
    .fontSize(24)
    .text(BRAND.document.title, {
      align: "center"
    });

  doc.moveDown();

  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor(BRAND.colors.lightText)

  doc.text(`Report ID : ${reportId}`);
  doc.text(`Generated : ${new Date().toLocaleString()}`);
  doc.text("AI Engine : Trulexity AI");
  doc.text("Status : Completed");

  doc.moveDown();
}
function drawSectionTitle(doc, title) {
  doc.moveDown(0.3);

  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor(BRAND.colors.primary)
    .text(title);

  doc.moveDown(0.4);

  doc
    .moveTo(doc.page.margins.left, doc.y)
.lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor(BRAND.colors.accent)
    .lineWidth(1)
    .stroke();

  doc.moveDown(0.3);
}

function drawParagraph(doc, text) {

  text = String(text || "")
  .replace(/✅\s*/g, "")
  .replace(/📖\s*/g, "")
  .replace(/❌\s*/g, "")
  .replace(/🔍\s*/g, "")
  .replace(/📌\s*/g, "")
  .replace(/🎯\s*/g, "")
  .replace(/💡\s*/g, "")
  .replace(/\r/g, "")
  .replace(/\n{3,}/g, "\n\n")
  .replace(/[ \t]{2,}/g, " ")
  .trim();

  doc
  .font("Helvetica")
  .fontSize(12)
  .fillColor(BRAND.colors.text);

console.log("DRAWING PARAGRAPH");
console.log("Current Y:", doc.y);
console.log("Text length:", text.length);

doc.text(
  text,
  doc.page.margins.left,
  doc.y,
  {
    width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
    align: "left",
    lineGap: 5,
  }
);
console.log("After text Y:", doc.y);
  doc.moveDown(0.4);
}
function drawFooter(doc, metadata) {

  const range = doc.bufferedPageRange();

  for (let i = 0; i < range.count; i++) {

    doc.switchToPage(i);

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#777777");

    doc.text(
      `Generated by Trulexity AI`,
      60,
      doc.page.height - 40
    );

    doc.text(
      `Page ${i + 1} of ${range.count}`,
      0,
      doc.page.height - 40,
      {
        align: "right"
      }
    );
  }

}


function drawCoverPage(doc, metadata) {

  // Dark Background
  doc.save();
  doc.rect(0, 0, doc.page.width, doc.page.height)
     .fill("#0B1F3A");
  doc.restore();

  // Brand Name
  doc
    .font("Helvetica-Bold")
    .fontSize(42)
    .fillColor("#FFFFFF")
    .text("TRUVORA", 0, 70, {
      align: "center",
    });

  doc
    .font("Helvetica")
    .fontSize(18)
    .fillColor("#4FC3F7")
    .text("GLOBAL AI TECHNOLOGIES", {
      align: "center",
    });

  doc.moveDown();

  doc
    .fontSize(13)
    .fillColor("#B3E5FC")
    .text("INTELLIGENCE • INNOVATION • TRUST", {
      align: "center",
    });

  doc.moveDown(4);

  doc
    .font("Helvetica-Bold")
    .fontSize(30)
    .fillColor("#FFFFFF")
    .text("AI ANALYSIS REPORT", {
      align: "center",
    });

  doc.moveDown(3);

  doc
    .font("Helvetica")
    .fontSize(14)
    .fillColor("#FFFFFF");

  doc.text(`Report ID : ${metadata.reportId}`);
  doc.text(`Generated : ${metadata.generatedAt}`);
  doc.text(`AI Engine : Trulexity AI`);
  doc.text(`Status : Verified`);
  doc.text(`Website : trulexity.com`);

  doc.moveDown(4);

  doc
    .font("Helvetica-Bold")
    .fontSize(16)
    .fillColor("#4FC3F7")
    .text("CONFIDENTIAL", {
      align: "center",
    });

  doc.moveDown();

  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#FFFFFF")
    .text(
      "Generated by Trulexity AI\nFor authorized use only.",
      {
        align: "center",
      }
    );

  doc.addPage();
}
function drawTableOfContents(doc, document) {

  doc
    .font("Helvetica-Bold")
    .fontSize(30)
    .fillColor(BRAND.colors.primary)
    .text("Table of Contents");

  doc.moveDown(1.5);

  const sections = [
  { no: 1, title: "Executive Summary", page: 3 },
  { no: 2, title: "Detailed Analysis", page: 3 },
  { no: 3, title: "Recommendations", page: 4 },
  { no: 4, title: "Sources", page: 4 }
];

  doc
    .font("Helvetica")
    .fontSize(16)
    .fillColor(BRAND.colors.text);

  sections.forEach((section, index) => {

  const page = section.page || index + 3;

  doc.text(
    `${section.no}. ${section.title}`,
    {
      continued: true
    }
  );

  doc.text(
    ` ........................................ ${page}`,
    {
      align: "right"
    }
  );

  doc.moveDown(0.7);

});

  doc.addPage();

}
async function generatePDF({
  outputPath,
  reportId,
  title,
  summary,
  analysis,
  recommendations,
  sources
}) {
const document = prepareDocument(
  {
  reportId,
  title,
  summary,
  analysis,
  recommendations,
  sources: sources
},
"pdf"
);

const metadata = document.metadata;
const report = document.report;

const doc = createPdf(outputPath);
console.log("Page after createPdf:", doc.bufferedPageRange().count);
drawCoverPage(doc, metadata);
console.log("Page after Cover:", doc.bufferedPageRange().count);
drawTableOfContents(doc, document);
console.log("Page after TOC:", doc.bufferedPageRange().count);
drawHeader(doc, metadata.reportId);
console.log("SUMMARY:");
console.log(report.summary.content);

console.log("SUMMARY LENGTH:");
console.log(report.summary.content.length);

console.log("ANALYSIS:");
console.log(report.analysis.content);

console.log("ANALYSIS LENGTH:");
console.log(report.analysis.content.length);

// ---------- SUMMARY ----------
console.log("Current Y:", doc.y);

drawSectionTitle(doc, report.summary.title);

console.log("SUMMARY DRAW LENGTH:");
console.log(report.summary.content.length);

drawParagraph(doc, report.summary.content);

console.log("Page after Summary:", doc.bufferedPageRange().count);
console.log("After Summary Y:", doc.y);
// ---------- ANALYSIS ----------
drawSectionTitle(doc, report.analysis.title);

console.log("ANALYSIS DRAW LENGTH:");
console.log(report.analysis.content.length);

drawParagraph(doc, report.analysis.content);
console.log("Page after Analysis:", doc.bufferedPageRange().count);
console.log("After Analysis Y:", doc.y);
// ---------- CONFIDENCE ----------
if (report.confidence) {
  drawSectionTitle(doc, report.confidence.title);
  drawParagraph(doc, report.confidence.content);
}

// ---------- RECOMMENDATIONS ----------
console.log("RECOMMENDATIONS:");
console.log(report.recommendations.content);


drawSectionTitle(doc, report.recommendations.title);
drawParagraph(doc, report.recommendations.content);
console.log("Page after Recommendations:", doc.bufferedPageRange().count);
console.log("After Recommendations Y:", doc.y);
// ---------- SOURCES ----------
console.log("SOURCES:");
console.log(report.sources.content);

drawSectionTitle(doc, report.sources.title);
drawParagraph(doc, report.sources.content);
console.log("Page after Sources:", doc.bufferedPageRange().count);
console.log("After Sources Y:", doc.y);
// ---------- FOOTER ----------
// drawFooter(doc, metadata);

// drawFooter(doc, metadata);

doc.end();

return outputPath;
}

export { generatePDF };
