import PptxGenJS from "pptxgenjs";

export async function generatePPTX({
  outputPath,
  reportId,
  title,
  summary,
  analysis,
  recommendations,
  sources,
}) {
  const pptx = new PptxGenJS();

  // ============================
  // Presentation Properties
  // ============================
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Truvora Global AI";
  pptx.company = "Truvora Global AI Technologies";
  pptx.subject = title || "AI Analysis Report";
  pptx.title = title || "Truvora AI Report";
  pptx.lang = "en-US";

  // ============================
  // Brand Colors
  // ============================
  const COLORS = {
    PRIMARY: "1565C0",
    SECONDARY: "0D47A1",
    ACCENT: "29B6F6",
    TEXT: "222222",
    LIGHT: "777777",
    WHITE: "FFFFFF",
    BORDER: "DDDDDD",
    BG: "F7F9FC",
    SUCCESS: "2E7D32",
    LINK: "0563C1",
  };

  const totalSlides = 5;

  // ============================
  // Common Slide Style
  // ============================
  function decorateSlide(slide, page) {
    slide.background = {
      color: COLORS.WHITE,
    };

    // Header Bar
    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.33,
      h: 0.25,
      line: {
        color: COLORS.PRIMARY,
        transparency: 100,
      },
      fill: {
        color: COLORS.PRIMARY,
      },
    });

    // Footer Line
    slide.addShape(pptx.ShapeType.line, {
      x: 0,
      y: 7.1,
      w: 13.33,
      h: 0,
      line: {
        color: COLORS.BORDER,
        width: 1,
      },
    });

    slide.addText("Generated by Truvora Global AI", {
      x: 0.45,
      y: 7.15,
      w: 5,
      h: 0.2,
      fontFace: "Calibri",
      fontSize: 9,
      color: COLORS.LIGHT,
      italic: true,
    });

    slide.addText(`${page} / ${totalSlides}`, {
      x: 12.0,
      y: 7.15,
      w: 0.8,
      h: 0.2,
      align: "right",
      fontFace: "Calibri",
      fontSize: 9,
      color: COLORS.LIGHT,
    });
  }

  // ============================
  // Slide 1 - Cover
  // ============================

  let slide = pptx.addSlide();

  decorateSlide(slide, 1);

  slide.addText("TRUVORA GLOBAL AI", {
    x: 0.6,
    y: 0.6,
    w: 8,
    h: 0.5,
    fontFace: "Calibri",
    fontSize: 28,
    bold: true,
    color: COLORS.PRIMARY,
  });

  slide.addText("Intelligence • Innovation • Trust", {
    x: 0.6,
    y: 1.05,
    w: 8,
    h: 0.3,
    fontFace: "Calibri",
    fontSize: 14,
    italic: true,
    color: COLORS.LIGHT,
  });
    slide.addText(`Report ID: ${reportId || "N/A"}`, {
    x: 0.6,
    y: 1.65,
    w: 4,
    h: 0.3,
    fontFace: "Calibri",
    fontSize: 12,
    color: COLORS.TEXT,
  });

  slide.addText(title || "AI Analysis Report", {
    x: 0.6,
    y: 2.2,
    w: 12,
    h: 0.8,
    fontFace: "Calibri",
    fontSize: 24,
    bold: true,
    color: COLORS.TEXT,
  });

  slide.addShape(pptx.ShapeType.rect, {
    x: 0.6,
    y: 3.25,
    w: 12,
    h: 2.3,
    line: {
      color: COLORS.BORDER,
      width: 1,
    },
    fill: {
      color: COLORS.BG,
    },
  });

  slide.addText(
    "This report has been generated automatically by Truvora Global AI using advanced AI analysis and trusted information sources.",
    {
      x: 0.85,
      y: 3.55,
      w: 11.4,
      h: 1.6,
      fontFace: "Calibri",
      fontSize: 18,
      color: COLORS.TEXT,
      valign: "mid",
      align: "center",
      margin: 0.05,
    }
  );

  // ==================================
  // Slide 2 - Executive Summary
  // ==================================

  slide = pptx.addSlide();
  decorateSlide(slide, 2);

  slide.addText("Executive Summary", {
    x: 0.6,
    y: 0.5,
    w: 8,
    h: 0.4,
    fontFace: "Calibri",
    fontSize: 22,
    bold: true,
    color: COLORS.PRIMARY,
  });

  slide.addShape(pptx.ShapeType.line, {
    x: 0.6,
    y: 0.95,
    w: 2.8,
    h: 0,
    line: {
      color: COLORS.ACCENT,
      width: 2,
    },
  });

  slide.addText(summary || "No summary available.", {
    x: 0.6,
    y: 1.2,
    w: 12,
    h: 5.7,
    fontFace: "Calibri",
    fontSize: 16,
    color: COLORS.TEXT,
    valign: "top",
    margin: 0.08,
    breakLine: false,
  });

  // ==================================
  // Slide 3 - Detailed Analysis
  // ==================================

  slide = pptx.addSlide();
  decorateSlide(slide, 3);

  slide.addText("Detailed Analysis", {
    x: 0.6,
    y: 0.5,
    w: 8,
    h: 0.4,
    fontFace: "Calibri",
    fontSize: 22,
    bold: true,
    color: COLORS.PRIMARY,
  });

  slide.addShape(pptx.ShapeType.line, {
    x: 0.6,
    y: 0.95,
    w: 2.8,
    h: 0,
    line: {
      color: COLORS.ACCENT,
      width: 2,
    },
  });

  slide.addText(analysis || "No analysis available.", {
    x: 0.6,
    y: 1.2,
    w: 12,
    h: 5.7,
    fontFace: "Calibri",
    fontSize: 15,
    color: COLORS.TEXT,
    valign: "top",
    margin: 0.08,
  });
    // ==================================
  // Slide 4 - Recommendations
  // ==================================

  slide = pptx.addSlide();
  decorateSlide(slide, 4);

  slide.addText("Recommendations", {
    x: 0.6,
    y: 0.5,
    w: 8,
    h: 0.4,
    fontFace: "Calibri",
    fontSize: 22,
    bold: true,
    color: COLORS.PRIMARY,
  });

  slide.addShape(pptx.ShapeType.line, {
    x: 0.6,
    y: 0.95,
    w: 2.8,
    h: 0,
    line: {
      color: COLORS.ACCENT,
      width: 2,
    },
  });

  slide.addText(recommendations || "No recommendations available.", {
    x: 0.6,
    y: 1.2,
    w: 12,
    h: 5.7,
    fontFace: "Calibri",
    fontSize: 15,
    color: COLORS.TEXT,
    valign: "top",
    margin: 0.08,
  });

  // ==================================
  // Slide 5 - Sources
  // ==================================

  slide = pptx.addSlide();
  decorateSlide(slide, 5);

  slide.addText("Sources", {
    x: 0.6,
    y: 0.5,
    w: 8,
    h: 0.4,
    fontFace: "Calibri",
    fontSize: 22,
    bold: true,
    color: COLORS.PRIMARY,
  });

  slide.addShape(pptx.ShapeType.line, {
    x: 0.6,
    y: 0.95,
    w: 2.8,
    h: 0,
    line: {
      color: COLORS.ACCENT,
      width: 2,
    },
  });

  let y = 1.25;

  if (Array.isArray(sources) && sources.length > 0) {
    sources.forEach((url, index) => {
      slide.addText(
  [
    {
      text: `${index + 1}. ${url}`,
      options: {
        hyperlink: {
          url: url,
        },
      },
    },
  ],
  {
    x: 0.7,
    y,
    w: 11.7,
    h: 0.28,
    fontFace: "Calibri",
    fontSize: 12,
    color: COLORS.LINK,
    underline: true,
  }
);

      y += 0.35;

      if (y > 6.5) return;
    });
  } else {
    slide.addText("No sources available.", {
      x: 0.7,
      y: 1.25,
      w: 11,
      h: 0.3,
      fontFace: "Calibri",
      fontSize: 14,
      color: COLORS.TEXT,
    });
  }
    // ==================================
  // Save Presentation
  // ==================================

  await pptx.writeFile({
    fileName: outputPath,
  });

  return outputPath;
}