import fs from "fs";

export async function generateTXT({
  outputPath,
  reportId,
  title,
  summary,
  analysis,
  recommendations,
  sources,
}) {
  const content = `
TRUVORA
${title}

Report ID: ${reportId}
Generated: ${new Date().toLocaleString()}

==================================================
EXECUTIVE SUMMARY
==================================================

${summary || "No summary available."}

==================================================
DETAILED ANALYSIS
==================================================

${analysis || "No analysis available."}

==================================================
RECOMMENDATIONS
==================================================

${recommendations || "No recommendations available."}

==================================================
SOURCES
==================================================

${
  Array.isArray(sources)
    ? sources.map((s) => "- " + s).join("\n")
    : "No sources available."
}

==================================================

Generated by TRUVORA Global AI
Intelligence • Innovation • Trust
`;

  fs.writeFileSync(outputPath, content, "utf8");

  return outputPath;
}